dist: trusty
sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - develop
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- npm update
script:
- npm test
after_script:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js